swagger: "2.0"
info:
  version: "0.0.1"
  title: "graphvisualization"
  description: ""
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Visualize Workflows REST Service"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/flow"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "text/html"
paths:
  /monitor:
    get:
      tags:
        - monitor
      operationId: render.show
      description: "It returns a sample graph."
      produces:
        - "text/html"
      responses:
        201:
          description: A sample workflow


    post:
      operationId: render.update
      tags:
        - monitor
      summary: Monitor a workflow depicted as a graph
      description: Monitor a workflow depicted as a graph
      parameters:
        - name: workflow
          in: body
          description: Workflow to visualize
          required: False
          schema:
            $ref: "#/definitions/workflow"
      responses:
        201:
          description: Successfully created a digram for the workflow
definitions:
  workflow:
    type: "object"
    required:
      - "flowyaml"

    properties:
      flowyaml:
        type: "string"
