tasks:
    a:

      parameter:
         x: "int"
         y:: "int"
      calculation: f(x,y)
      entry:
         color: green
         label: a
         value: x
         shape: circle
      return:
         color: green
         label: a
         value: x
         shape: circle
    b:

      parameter:
        x: "int"
        y:: "int"
      calculation: g(x,y)
      entry:
        color: green
        label: b
        value: x
        shape: circle
      return:
        color: green
        label: b
        value: x
        shape: circle